type: generic
docroot: ""
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
hooks:
    post-start:
        - exec: npm install
omit_containers: [db, ddev-ssh-agent]
use_dns_when_possible: true
composer_version: ""
web_environment: []
nodejs_version: auto
corepack_enable: false
ddev_version_constraint: '>= v1.24.10'
